FROM registry.cn-hangzhou.aliyuncs.com/mxvc/openjdk:17-alpine

# 黑体
ADD fonts/simhei.ttf /usr/share/fonts/chinese/
ADD fonts/simhei.ttf /$JAVA_HOME/jre/lib/fonts/

# 宋体
ADD fonts/simsun.ttc /usr/share/fonts/chinese/
ADD fonts/simsun.ttc /$JAVA_HOME/jre/lib/fonts/


