db_ip: 127.0.0.1
db_port: 3306
db_database: tmgg-sys
db_username: root
db_password: 123456
spring:
  profiles:
    active: default

sys:
  cache-dir: /tmgg/framework/cache

logging:
  file:
    path: ../logs/app-log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
