dao.java.template=${moduleFile}/dao/${name}Dao.java
service.java.template=${moduleFile}/service/${name}Service.java
controller.java.template=${moduleFile}/controller/${name}Controller.java
menu.sql.template=${resourcesDir}/db/migration/R__menu.sql
