dao.java.template=${moduleFile}/dao/${name}Dao.java
service.java.template=${moduleFile}/service/${name}Service.java
controller.java.template=${moduleFile}/controller/${name}Controller.java
menu.json=${resourcesDir}/database/menu_${underlineName}.json
