name: base-docker-image-aliyun

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  base-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: mvn build
        run: mvn package -q -DskipTests=true

      - name:  Publish
        run: |
          cd tmgg-script/tmgg-script-docker/target
          java -jar app-jar-with-dependencies.jar  ${{ secrets.ALIYUN_REGISTRY_PASSWORD }} 
