name: 创建项目模板

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central

      - name: Publish MAVEN
        run: mvn -q deploy

      - name: 发布
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/ci/**/*.*


