name: Aliyun Docker Base Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  push_to_registry:
    name: Push Docker image to Aliyun
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses:  docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: hustme
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: registry.cn-hangzhou.aliyuncs.com/mxvc/docker-admin

      - name: tmgg-base-maven
        uses: docker/build-push-action@v6
        with:
          file: ./docker-base/tmgg-base-maven/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=1.0.0


      - name: tmgg-base-node
        uses: docker/build-push-action@v6
        with:
          file: ./docker-base/tmgg-base-maven/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      - name: tmgg-base-jdk
        uses: docker/build-push-action@v6
        with:
          file: ./docker-base/tmgg-base-jdk/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
