name: 项目模板

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  template:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: 清理不用的文件
        run: rm -rf templates/backend-template/assets
      - name: 压缩模板
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: ./templates
          files: |
            ./backend-template
         # outPath: backend-template.tar.gz
      - name: 查看结果
        run: |
          pwd
          ls
      - name: 发布模板压缩包
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /home/runner/work/tmgg/tmgg/*.tar.gz
