# https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish NPM, Maven

on:
  workflow_dispatch:
  push:

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Publish MAVEN
        # -rf :tmgg-dev-script
        run: mvn -DskipTests=true deploy -P publishMavenCentral
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE_KEY }}
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: publish npm
        run: npm install pnpm -g &&  cd web-monorepo && pnpm install &&  pnpm publish -r --access public --no-git-checks

        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
      - name: 同步阿里云镜像仓库
        run: |
          npm install -g cnpm --registry=https://registry.npmmirror.com 
          cnpm sync @tmgg/tmgg-base  
          cnpm sync @tmgg/tmgg-commons-lang 
          cnpm sync @tmgg/tmgg-system
          cnpm sync @tmgg/tmgg-system-job
          cnpm sync @tmgg/tmgg-system-code-gen
          cnpm sync @tmgg/tmgg-system-flowable



